In [16]:
from absenteeism_module import *

In [17]:
pd.read_csv('Absenteeism_new_data.csv')

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pet
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0
5,28,11,11/06/2018,225,26,28,237.656,24,1,1,2
6,16,7,13/06/2018,118,15,46,275.089,25,1,2,0
7,22,27,13/06/2018,179,26,30,275.089,19,3,0,0
8,34,26,15/06/2018,118,10,37,275.089,28,1,0,0
9,34,10,20/06/2018,118,10,37,275.089,28,1,0,0
10,23,22,21/06/2018,378,49,36,275.089,21,1,2,4
11,36,19,21/06/2018,118,13,50,275.089,31,1,1,0
12,12,19,22/06/2018,233,51,31,275.089,21,2,1,8
13,22,27,22/06/2018,179,26,30,275.089,19,3,0,0
14,2,0,25/06/2018,235,29,48,275.089,33,1,1,5
15,21,0,28/06/2018,268,11,33,275.089,25,2,0,0
16,36,19,28/06/2018,118,13,50,275.089,31,1,1,0
17,22,13,28/06/2018,179,26,30,275.089,19,3,0,0
18,15,28,28/06/2018,291,31,40,275.089,25,1,1,1
19,22,13,02/07/2018,179,26,30,275.089,19,3,0,0
20,34,25,02/07/2018,118,10,37,275.089,28,1,0,0
21,12,22,05/07/2018,233,51,31,275.089,21,2,1,8
22,34,8,06/07/2018,118,10,37,275.089,28,1,0,0
23,34,10,11/07/2018,118,10,37,275.089,28,1,0,0
24,12,22,11/07/2018,233,51,31,275.089,21,2,1,8
25,5,26,11/07/2018,235,20,43,264.604,38,1,1,0
26,12,19,13/07/2018,233,51,31,264.604,21,2,1,8
27,9,6,16/07/2018,228,14,58,264.604,22,1,2,1
28,34,28,16/07/2018,118,10,37,264.604,28,1,0,0
29,9,6,17/07/2018,228,14,58,264.604,22,1,2,1
30,6,22,17/07/2018,189,29,33,264.604,25,1,2,2
31,34,23,18/07/2018,118,10,37,264.604,28,1,0,0
32,10,22,18/07/2018,361,52,28,264.604,27,1,1,4
33,28,22,18/07/2018,225,26,28,264.604,24,1,1,2
34,13,13,23/07/2018,369,17,31,264.604,25,1,3,0
35,11,14,24/07/2018,289,36,33,264.604,30,1,2,1
36,1,11,24/07/2018,235,11,37,264.604,29,3,1,1
37,4,0,24/07/2018,118,14,40,271.219,34,1,1,8
38,8,0,25/07/2018,231,35,39,271.219,35,1,2,2
39,35,0,27/07/2018,179,45,53,271.219,25,1,1,1

In [18]:
model = absenteeism_model('model', 'scaler')

In [19]:
model.load_and_clean_data('Absenteeism_new_data.csv')

KeyError: "['Pets'] not in index"

In [20]:
print(model.data)

None

In [21]:
model.predicted_outputs()